### ISSUE TITLE
Neos.Seo:StructuredData.Website does not render name and url

### ISSUE THREAD

**Issue by markuspfeifenberger** [neos/neos-seo#163] opened 2021-10-20 13:42 UTC
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Version: latest

### What you did
The name and url are not rendered by default, only if additional props are define like decription, that everything works fine.

### Expected Behavior
```
{
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Site Name",
    "url": "http://localhost/"
}
```
### Actual Behavior
```
{
    "@context": "http://schema.org",
    "@type": "WebSite"
}
```

**Comment by Sebobo** [comment] 2024-01-10 09:35
Cannot reproduce this, probably fixed in the meanwhile in Fusion. Please reopen if this is still a problem with detailed version information.

**Closed by Sebobo** 2024-01-10 09:35 UTC
